// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cydttgspwnfupsopwepj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5ZHR0Z3Nwd25mdXBzb3B3ZXBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NTg5MzEsImV4cCI6MjA1MDUzNDkzMX0.MqyowqRm5lqjiaQYzx-dfFOoT726-u6lUYTu2egUIZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);